apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-handler-ingress
  labels:
    app: file-handler
    component: file-storage
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.test.buerokratt.ee
      secretName: file-handler-tls
  rules:
    - host: files.test.buerokratt.ee
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: file-handler
                port:
                  number: 3000
